version: '3.4'

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - mongo
    environment:
      MONGO_URL: ${MONGO_URL}
      IP : ${IP}
    restart: unless-stopped
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      PROD: ${PROD}
      IP : ${IP}
    restart: unless-stopped
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - data-volume:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  data-volume:
