DELETE  http://localhost:5000/api/books/id/62025939737caed296018250 HTTP/1.1
content-type: application/json

###
# Invalid Id Format
DELETE http://localhost:5000/api/books/ HTTP/1.1
content-type: application/json


###