DELETE  http://localhost:5000/api/book/ HTTP/1.1
content-type: application/json

{
    "id": "62020b2a4c4177dbd9f8b507"
}

###
# Invalid Id Format
DELETE http://localhost:5000/api/book/ HTTP/1.1
content-type: application/json

{
    "id": "620209c36d38f37eb264995ff"
}

###