DELETE  http://localhost:5000/api/books/id/62020ce99c771bc2061f6d86 HTTP/1.1
content-type: application/json

###
# Invalid Id Format
DELETE http://localhost:5000/api/books/ HTTP/1.1
content-type: application/json


###