GET http://localhost:5000/api/book/reading HTTP/1.1

###

GET http://localhost:5000/api/book/finished/ HTTP/1.1

###

GET http://localhost:5000/api/book/finished/1 HTTP/1.1

###

GET http://localhost:5000/api/book/finished/2 HTTP/1.1

###

GET http://localhost:5000/api/book/finished/99999999 HTTP/1.1