GET http://localhost:5000/api/books/reading HTTP/1.1

###

GET http://localhost:5000/api/books/finished/ HTTP/1.1

###

GET http://localhost:5000/api/books/finished/?page=1 HTTP/1.1

###

GET http://localhost:5000/api/books/finished/?page=2 HTTP/1.1

###

GET http://localhost:5000/api/books/finished/?page=99999999 HTTP/1.1

###

GET http://localhost:5000/api/books/id/62020ce79c771bc2061f6d8 HTTP/1.1